spring.application.name=CityWhisper

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/citywhisper_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Criação/atualização automática das tabelas com base nas entidades
spring.jpa.hibernate.ddl-auto=create

# Exibir o SQL gerado no console
spring.jpa.show-sql=true

# Formatar o SQL no console (mais legível)
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Permite execução de import.sql automaticamente
spring.sql.init.mode=always